<?php

namespace Heyimphil\Robotson\Models;

use SilverStripe\CMS\Model\SiteTree;
use SilverStripe\Forms\LiteralField;
use Silverstripe\ORM\DataObject;
use SilverStripe\SiteConfig\SiteConfig;

class RobotRule extends DataObject
{
    //TODO: review versioning compared to enabled. Probably achieve better result
    private static $db = [
        'Enabled' => 'Boolean',
        'UserAgent' => 'Varchar',
        'IncludeChildren' => 'Boolean',
        'CrawlDelay' => 'Int'
    ];

    private static $has_one = [
        'SiteConfig' => SiteConfig::class,
        'SiteTree' => SiteTree::class
    ];

    private static $summary_fields = [
        'UserAgent',
        'IncludeChildren'
    ];

    private static $table_name = 'RobotRule';

    public function getCMSFields()
    {
        $fields = parent::getCMSFields();

        //TODO: review the removal of include children on site config page. Most likely a parent class.
        if ($this->record['SiteConfigID']) {
            $fields->removeByName('IncludeChildren');
        }

        $fields->removeByName('SiteConfigID');
        $fields->removeByName('SiteTreeID');
        $fields->insertAfter('CrawlDelay',
            LiteralField::create(
                'DelayHeader',
                '<p>If you set a crawl delay to this user agent it will affect all Robot rules that contain this user agent</p>'
            )
        );

        return $fields;
    }

    public function Link()
    {
        if ($this->SiteTreeID) {
            return $this->SiteTree()->Link();
        }
        return '/';
    }

    public function validate()
    {
        //Each page can only have one rule per user agent

        return parent::validate(); // TODO: Change the autogenerated stub
    }
}
